name: flutter_frame_hyc
description: 自己封装的flutter基础框架底层包
version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_storage: 2.1.1
  path_provider: 2.0.14
  permission_handler: 10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
